ball_detector:
  ros__parameters:
    trackbar_initialized: false
    h_low_r: 0
    h_high_r: 17
    s_low_r: 80
    s_high_r: 255
    v_low_r: 80
    v_high_r: 255
    h_low_r2: 169
    h_high_r2: 179
    h_low_b: 85
    h_high_b: 130
    s_low_b: 0
    s_high_b: 255
    v_low_b: 0
    v_high_b: 255
    h_low_g: 35
    h_high_g: 85
    s_low_g: 0
    red_threshold: 0.8
    blue_threshold: 0.7
    green_threshold: 0.75

my_pure_pursuit_node:
  ros__parameters:
    lidar_offset_x: 0.286
    lidar_offset_y: -0.165
    lidar_offset_yaw: -1.047
    L: 0.33
    nav_radius: 0.3
    pgain_x: 0.5
    pgain_y: 1.0
    pgain_theta: 1.0

navigater_node:
  ros__parameters:
    blue_nav_point: [1.362, 3.5]
    yellow_nav_point: [1.8, 1.85]
    red_nav_point: [0.924, 5.112]
    notezone_entrance: [0.35, 5.888]
    wallDistance: 0.35


    